mariopartyrd/marioparty4

src/game/messdata.c
Introduced static functions are mentioned in adventure island map. Unnecessary register copies in ASM show them to be an option.
=> Label and clean up MessData_MesPtrGet

configure.py, include/game/hsfformat.h, include/game/hsfman.h, src/game/hsfman.c
=> hsfman.c functions match, variables need fixing

configure.py, include/game/card.h, src/game/card.c, src/game/saveload.c
Also start cleaning up saveload.c
=> Decompile card.c

configure.py, include/dolphin/dvd.h, src/msm/msmfio.c
=> Setup msm decompiling

config/GMPE01_00/rels/m401Dll/splits.txt, config/GMPE01_00/rels/m401Dll/symbols.txt, config/GMPE01_00/rels/m402Dll/splits.txt, config/GMPE01_00/rels/m403Dll/splits.txt, config/GMPE01_00/rels/m403Dll/symbols.txt, config/GMPE01_00/rels/m404Dll/splits.txt, config/GMPE01_00/rels/m404Dll/symbols.txt, configure.py
Split first 4 minigames in internal order (Manta Rings, Slime Time, Booksquirm, and Trace Race)
=> Split 4 minigames

config/GMPE01_00/rels/w01Dll/splits.txt, config/GMPE01_00/rels/w02Dll/splits.txt, config/GMPE01_00/rels/w03Dll/splits.txt, config/GMPE01_00/rels/w04Dll/splits.txt, config/GMPE01_00/rels/w05Dll/splits.txt, config/GMPE01_00/rels/w06Dll/splits.txt, config/GMPE01_00/rels/w10Dll/splits.txt, config/GMPE01_00/rels/w20Dll/splits.txt, config/GMPE01_00/rels/w21Dll/splits.txt, include/math.h, include/rel_sqrt_consts.h, src/REL/board_executor.c, src/REL/bootDll/main.c, src/REL/subchrselDll/main.c
Uses a new rel_sqrt_consts.h file
=> Introduce better fix to fake 0.5 and 3.0 double constants

configure.py, tools/ninja_syntax.py, tools/project.py
From https://github.com/encounter/dtk-template/commit/6debc74abf4a0a695adae4e69b340343a1893e70
Fixes issues using the assembler features on Windows.
=> Fix Windows path handling

src/game/board/mg_setup.c
initial structs, data, and functions
=> mg_setup beginnings

include/game/animdata.h, include/game/sprite.h, src/REL/bootDll/main.c, src/game/board/main.c, src/game/board/space.c, src/game/minigame_seq.c, src/game/sprman.c, src/game/sprput.c, src/game/thpmain.c, src/game/window.c
Also improved struct labeling.
=> Clean Up Sprite Constant Labeling

src/REL/modeseldll/filesel.c
fn_1_3AAC still not matched. I suspect prototype problems for that function.
=> Match most of of filesel.c

include/game/window.h, src/REL/bootDll/main.c, src/REL/instDll/main.c, src/REL/modeseldll/modesel.c
fn_1_2490 is down to one weird register allocation issue
=> Cleanups and almost finish modeseldll

src/REL/m404Dll/main.c
fn_1_5E74 and fn_1_607C still unsolved.
=> Figure out most remaining functions of m404dll

configure.py, include/ext_math.h, include/game/hsfman.h, src/REL/m410Dll/game.c, src/REL/m410Dll/main.c
Match first translation unit and much of game.c
=> Various m410dll fixes

configure.py, src/REL/m446Dll/main.c
=> Fix fn_1_CA0

src/REL/w02Dll/dice.c
work in progress, there might be a global struct definition that needs to be updated for this to work, but I forgot already. lol
=> some work for w02 dice

src/REL/m426Dll/main.c
fn_1_330 and fn_1_6DC8 solved but fn_1_16F8 is incomplete
=> m426dll improvements

.gitattributes, .github/workflows/build.yml, README.md, config/GMPE01_00/splits.txt, configure.py, tools/decompctx.py, tools/download_tool.py, tools/project.py
Among other changes, this will generate a progress report for https://decomp.dev
=> Update to latest dtk-template

include/dolphin/gx/GXVert.h, src/game/hsfdraw.c
I just accidentally found this project (I was looking for example of GX_VA_NBT usage in github) and noticed that something was not right with the constants. :-)
I did build the project (it builds without errors), but it's not clear to me how to run the built version in the emulator; it would be nice if this was added to the README.
=> Fix vertex attributes

configure.py
=> Truly Finish m438Dll

.vscode/settings.json, configure.py, src/MSL_C.PPCEABI.bare.H/abort_exit.c, src/MSL_C.PPCEABI.bare.H/mem.c
Credit to CelestialAmber for __memrchr in mem.c
=> Match MSL_C/abort_exit.c and MSL_C/mem.c

configure.py, include/PowerPC_EABI_Support/Msl/MSL_C/MSL_Common/ansi_files.h, include/string.h, src/MSL_C.PPCEABI.bare.H/alloc.c, src/MSL_C.PPCEABI.bare.H/printf.c, src/MSL_C.PPCEABI.bare.H/signal.c, src/MSL_C.PPCEABI.bare.H/string.c
These functions were mostly copied or modified from the Xenoblade decompilation project: [Xenoblade](https://github.com/xbret/xenoblade)
=> MSL: match alloc/signal/string and most of printf

configure.py, src/REL/modeseldll/modesel.c
=> Match modesel.c

src/game/board/basic_space.c
Added doxygen-compatible comments to
- game/board/basic_space.BoardLandBlueExec
- game/board/basic_space.BoardLandRedExec
Default output will look like this:
Please tear this apart. I'd like to keep documenting functions and want to ensure it's up to the standards expected of the project
=> Documented BoardLandBlueExec and BoardLandRedExec

tools/build_iso.py, tools/doc_check.py
Two Python scripts to assist with different things
A script for taking built C files and compiling them to an ISO file to work with an emulator or on console. Will likely be made obsolete as soon as a PC port exists, but it's nice to have until then.
A script for checking how much of the codebase has been documented. Useful to find what still needs commenting.
EX:
```
...
File                            Doc % Total      Unlabelled Vars
----------------------------------------------------------------
src/game\armem.c              : 00.00% (0/18)  : 0
src/game\audio.c              : 00.00% (0/53)  : 1
src/game\card.c               : 00.00% (0/15)  : 0
src/game\chrman.c             : 00.00% (0/58)  : 129
src/game\ClusterExec.c        : 00.00% (0/5)   : 25 
src/game\code_8003FF68.c      : …
```
=> Added two new tool scripts. build_iso.py and doc_check.py

include/dolphin/mtx.h, src/game/mapspace.c, src/libhu/setvf.c
I aim to add symbols to as many things as I can in this file. However, before I get in too deep I want to check with maintainers:
- Is this direction something you're open to merging?
- Am I following the project's standards closely enough so far?
Thanks 😎
=> RFC - adding symbols to mapspace.c 

config/GMPE01_00/build.sha1, config/GMPE01_00/config.yml, config/GMPE01_01/build.sha1, config/GMPE01_01/config.yml, config/GMPJ01_00/build.sha1, config/GMPJ01_00/config.yml, config/GMPP01_00/build.sha1, config/GMPP01_00/config.yml, config/GMPP01_02/build.sha1, config/GMPP01_02/config.yml, configure.py, tools/project.py
Compiler nondeterminism be gone
=> 100% linked

README.md
=> Mention USA version is complete in readme
